### ISSUE TITLE
Correct issues in the unit tests where they're deadlocking

### ISSUE THREAD

**Issue by benjivesterby** [benjivesterby/atomizer#3]
$ go test -run=.
fatal error: all goroutines are asleep - deadlock!

goroutine 1 [chan receive]:
testing.(*T).Run(0xc0000ca100, 0x55f348, 0x17, 0x565c20, 0x4765bd)
        c:/go/src/testing/testing.go:917 +0x388
testing.runTests.func1(0xc0000ca000)
        c:/go/src/testing/testing.go:1157 +0x7f
testing.tRunner(0xc0000ca000, 0xc000093e30)
        c:/go/src/testing/testing.go:865 +0xc7
testing.runTests(0xc000062440, 0x6632c0, 0x6, 0x6, 0x0)
        c:/go/src/testing/testing.go:1155 +0x2b0
testing.(*M).Run(0xc0000b6000, 0x0)
        c:/go/src/testing/testing.go:1072 +0x169
main.main()
        _testmain.go:62 +0x145

goroutine 19 [semacquire]:
sync.runtime_SemacquireMutex(0x682058, 0x0)
        c:/go/src/runtime/sema.go:71 +0x44
sync.(*RWMutex).Lock(0x682050)
        c:/go/src/sync/rwmutex.go:98 +0x80
github.com/benjivesterby/atomizer/registration.Registrations(0x584e60, 0xc000064800, 0xc000064770)
        C:/Users/benja/go/src/github.com/benjivesterby/atomizer/registration/register.go:27 +0x38
github.com/benjivesterby/atomizer.(*atomizer).Exec.func1()
        C:/Users/benja/go/src/github.com/benjivesterby/atomizer/atomizer_exported.go:42 +0x50
sync.(*Once).Do(0xc0000b6168, 0xc0000d3db0)
        c:/go/src/sync/once.go:44 +0xba
github.com/benjivesterby/atomizer.(*atomizer).Exec(0xc0000b6100, 0x0, 0x0)
        C:/Users/benja/go/src/github.com/benjivesterby/atomizer/atomizer_exported.go:39 +0xa5
github.com/benjivesterby/atomizer.TestAtomizeNoConductors(0xc0000ca100)
        C:/Users/benja/go/src/github.com/benjivesterby/atomizer/atomizer_test.go:72 +0x275
testing.tRunner(0xc0000ca100, 0x565c20)
        c:/go/src/testing/testing.go:865 +0xc7
created by testing.(*T).Run
        c:/go/src/testing/testing.go:916 +0x361

goroutine 20 [chan send (nil chan)]:
github.com/benjivesterby/atomizer/registration.Registrations.func1.1.1(0x525160, 0xc00005c490, 0x53c9c0, 0xc000062460, 0x0)
        C:/Users/benja/go/src/github.com/benjivesterby/atomizer/registration/register.go:50 +0xa8
sync.(*Map).Range(0x666900, 0xc0000d5fa8)
        c:/go/src/sync/map.go:333 +0x147
github.com/benjivesterby/atomizer/registration.Registrations.func1.1(0x584e60, 0xc000064700)
        C:/Users/benja/go/src/github.com/benjivesterby/atomizer/registration/register.go:41 +0x8a
created by github.com/benjivesterby/atomizer/registration.Registrations.func1
        C:/Users/benja/go/src/github.com/benjivesterby/atomizer/registration/register.go:36 +0x4e

goroutine 21 [select]:
github.com/benjivesterby/atomizer.(*atomizer).receive.func1(0xc0000b6080, 0xc00005a4e0)
        C:/Users/benja/go/src/github.com/benjivesterby/atomizer/atomizer.go:128 +0x16e
created by github.com/benjivesterby/atomizer.(*atomizer).receive
        C:/Users/benja/go/src/github.com/benjivesterby/atomizer/atomizer.go:116 +0x80
exit status 2
FAIL    github.com/benjivesterby/atomizer       0.555s

**Comment by benjivesterby** [comment]
Corrected the majority of the deadlocking, but the final deadlock is actually due to the global mutex lock of the benchmark system which interferes with a sync.Map background global lock. This overlap causes a deadlock when running benchmarks.
